#!/bin/bash

# Templates are functions/snippets for general use.
# They are aliased preceded with "t-".
#
# The first argument should be a function defined internally, preceded with _.
#
# A program can be optionally specified as second argument; if it is not found
# in the PATH, then the template won't be defined.
#
# Similarly, you can specify a file as third argument. If the file is not found,
# then the template won't be defined either.
#
# Arguments:
#  $1: template name
#  $2: a program (e.g. vim or /usr/bin/vim)
#  $3: a file (e.g. /boot/grub/grub.cfg)
#
add_template() {
    [ ! "x$2" = "x" ] && ! command -v "$2" > /dev/null 2>&1 && return
    [ ! "x$3" = "x" ] && [ ! -e "$3" ] && return
    alias "t-$1"="_$1"
}

_pacman-diff-file() {
    if [ -z ${1:+x} ] ; then
        echo "Usage: t-pacman-diff-file <file>"
    elif [ -f "$1" ] ; then
        pkg="$(pacman -Qo "$1" | awk '//{printf "%s-%s", $(NF-1), $NF;}')"
        bsdtar -xOf "/var/cache/pacman/pkg/${pkg}-$(uname -m).pkg.tar.xz" "${1/\//}" | diff - "$1"
        return 0
    else
        echo "The provided file \\e[0;31m${1}\\e[0m does not exist."
        return 1
    fi
}
add_template pacman-diff-file pacman
