#!/bin/sh

# global env vars

if [ -z ${DOTFILES:+x} ] ; then
    # TODO: error
    echo "WARN: DOTFILES is not defined"
fi

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"



export MEDIA="/run/media/$USER"
export DISK_46A2="$MEDIA/4677801d-12d7-40d4-808b-f152e6273ba2/$USER"



#LANG="en_US.UTF-8"

export EDITOR="nano -c"
export BROWSER="firefox"

# WINE
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
#export WINEDLLOVERRIDES="winemenubuilder.exe=d;winedevice.exe=d"

# suppress logs "Couldn't connect to accessibility bus: ..."
export NO_AT_BRIDGE=1

export QT_AUTO_SCREEN_SCALE_FACTOR=0

# JVM default options
_JAVA_OPTIONS=" \
-Dcom.oracle.usagetracker.config.file=$DOTFILES/.java/usagetracker.properties \
-Djdk.disableLastUsageTracking=true \
"
export _JAVA_OPTIONS

#export XUSERFILESEARCHPATH=



# android
export ANDROID_HOME="/opt/android-sdk"
export ANDROID_SDK_HOME="$XDG_DATA_HOME/android-sdk"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"

# go
export GOPATH="$XDG_DATA_HOME/go"

export ASPELL_CONF="home-dir $XDG_CONFIG_HOME/aspell;"
export ATOM_HOME="$XDG_CONFIG_HOME/atom"
export GMVAULT_DIR="$XDG_CONFIG_HOME/gmvault"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export INPUTRC="$DOTFILES/.inputrc"
export IPELATEXDIR="$XDG_CACHE_HOME/ipe/latexrun"
export KDEHOME="$XDG_CONFIG_HOME/kde4"
export LESSHISTFILE=-
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/config"
export OPERA_PERSONALDIR="$XDG_CONFIG_HOME/opera"
export PROXYCHAINS_CONF_FILE="$XDG_CONFIG_HOME/proxychains.conf"
export UNISON="$DOTFILES/.unison"
export VIMINIT=":so $XDG_CONFIG_HOME/vim/vimrc"
export WGETRC="$DOTFILES/.wgetrc"

export RANDFILE="$XDG_CONFIG_HOME/.rnd"

export XAUTHORITY="$HOME/.Xauthority"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# nvidia
export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME/nv"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"



# private
export PRIVATE="$HOME/private"
export PASSWORD_STORE_DIR="$PRIVATE/.pass"
