source ~/.dotfiles/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect("~/.dotfiles/vim/bundle/{}")
syntax on
filetype plugin indent on

nmap \l :setlocal number!<CR>

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

set listchars=tab:→\-,trail:·,nbsp:·
set list

set cindent
set shiftwidth=4
set expandtab

set viminfo=

set directory^=~/.dotfiles/vim/tmp//

let g:vimwiki_list = [ { 'path' : '~/private/vimwiki' } ]
