source $DOTFILES/vim/autoload/pathogen.vim
execute pathogen#infect('$DOTFILES/vim/bundle/{}')
syntax on
filetype plugin indent on

nmap \l :setlocal number!<CR>

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

set listchars=tab:→\-,trail:·,nbsp:·
set list

set cindent
set shiftwidth=2
set expandtab

set viminfo=
