source $XDG_CONFIG_HOME/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('$XDG_CONFIG_HOME/vim/bundle/{}')
syntax on
filetype plugin indent on

nmap \l :setlocal number!<CR>

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

set listchars=tab:>-,nbsp:~,trail:·,eol:¶,precedes:«,extends:»
if has("patch-7.4.710")
    set listchars+=space:·
endif
set list

set cindent
set shiftwidth=4
set expandtab

set viminfo=

set directory^=$XDG_CONFIG_HOME/vim/swap//

let g:vimwiki_list = [ { 'path' : '$VIMWIKI_PATH' } ]
