#!/usr/bin/env python3

# see <https://docs.python.org/3/library/readline.html?highlight=readline#example>

import atexit
import os
import pathlib
import readline

CACHE_HOME = pathlib.Path(os.getenv("XDG_CACHE_HOME", pathlib.Path("~/.cache").expanduser()))
HIST_FILE = CACHE_HOME.joinpath(".python_history")
try:
    readline.read_history_file(HIST_FILE)
    # default history len is -1 (infinite), which may grow unruly
    readline.set_history_length(1000)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, HIST_FILE)

