#!/bin/sh
set -euf

run() {
  cmd="$1"
  shift

  sleep=
  if [ $# -ge 1 ] ; then
    sleep=$1
    shift
  fi

  if [ -z "$sleep" ] ; then
    ( exec "$cmd" "$@" > /dev/null 2>&1 ) &
  else
    ( sleep "$sleep" ; [ -z "$(pidof "$cmd")" ] && exec "$cmd" "$@" > /dev/null 2>&1 ) &
  fi
}

/usr/bin/xsetroot -solid black
/usr/bin/xset r rate 250 25
/usr/bin/xset b off

run "/usr/bin/uxterm" 1s

run "$HOME/.dotfiles/bin/fbpanel" 2s
run "$HOME/.dotfiles/bin/conky" 3s

run "/usr/bin/qxkb" 4s
run "/usr/bin/pasystray" 4s

run "/usr/bin/xscreensaver" 4s
run "/usr/bin/xss-lock" 5s -- xscreensaver-command -lock
