#!/bin/sh

run() {
  if [ $# -eq 1 ] ; then
    ( $1 &> /dev/null ) &
  fi
  if [ $# -eq 2 ] ; then
    ( sleep $2 ; [[ -z `pidof $1` ]] && $1 &> /dev/null ) &
  fi
}

/usr/bin/xsetroot -solid black
/usr/bin/xset r rate 250 25

run "/usr/bin/fbpanel" 1s
run "/usr/bin/uxterm" 1s

run "/usr/bin/qxkb" 2s

run "/usr/bin/xscreensaver" 5s
run "/usr/bin/xss-lock -- xscreensaver-command -lock" 5s

run "/usr/bin/conky" 5s
run "/usr/bin/pasystray" 5s
