#!/bin/sh
set -euf

OLD_SINK=$(pactl get-default-sink)
echo "$OLD_SINK"
NEW_SINK=$(pactl list short sinks | grep -v "$OLD_SINK" | awk '{ print $2 ; exit }')
echo "$NEW_SINK"
pactl set-default-sink "$NEW_SINK"

pactl list sink-inputs short | awk '{ print $1; }' | xargs -I {} -- pactl move-sink-input {} "$NEW_SINK"

dunstify "pactl: '$OLD_SINK' -> '$NEW_SINK'"
