#!/bin/bash
set -euf

DISPLAY=1
while [ -e "/tmp/.X11-unix/X$DISPLAY" ] ; do
    DISPLAY=$((DISPLAY + 1))
done
export DISPLAY=":$DISPLAY"

if false ; then
    xinit "$@" -- /usr/bin/Xvfb "$DISPLAY"
    exit 0
fi

XAUTHORITY=$(mktemp "/tmp/.Xauthority.XXXXXXXX")
trap "rm -- '$XAUTHORITY'" EXIT
export XAUTHORITY

MCOOKIE=$(mcookie)
xauth add "$DISPLAY" "MIT-MAGIC-COOKIE-1" "$MCOOKIE"

Xvfb "$DISPLAY" -nolisten tcp -terminate &
XVFBPID=$!
cleanup() {
    rv=$?
    /usr/bin/kill -s TERM --timeout 100 KILL -- "$XVFBPID" || true
    xauth remove "$DISPLAY" || true
    rm -- "$XAUTHORITY" || true
    exit $rv
}
trap cleanup EXIT HUP INT TERM
sleep 1

"$@"
