#!/bin/bash
set -euf

DISPLAY=1
while [ -e "/tmp/.X11-unix/X$DISPLAY" ] ; do
DISPLAY=$((DISPLAY + 1))
done
export DISPLAY=":$DISPLAY"

if false ; then
    xinit "$@" -- /usr/bin/Xvfb "$DISPLAY"
    exit 0
fi

XAUTHORITY="$(mktemp .Xauthority.XXXXXXXX)"
trap "rm -- '$XAUTHORITY'" EXIT
export XAUTHORITY

MCOOKIE=$(mcookie)
xauth add "$DISPLAY" "MIT-MAGIC-COOKIE-1" "$MCOOKIE"

Xvfb "$DISPLAY" -nolisten tcp -terminate &
XVFBPID=$!
cleanup() {
    rv=$?
    kill -SIGTERM -- "$XVFBPID"
    xauth remove "$DISPLAY"
    rm -- "$XAUTHORITY"
    exit $rv
}
trap cleanup EXIT
sleep 1

"$@"
