#

window:
  dimensions:
    columns: 110
    lines: 35

  padding:
    x: 2
    y: 2

  dynamic_padding: true

scrolling:
  multiplier: 5

selection:
  save_to_clipboard: true

cursor:
  style: Beam
