#

cursor:
  style: Beam
  thickness: 0.2

env:
  TERM: xterm-256color

selection:
  save_to_clipboard: true
  semantic_escape_chars: "\t \"'(),/:<>[]`{|}"

scrolling:
  multiplier: 5

window:
  dimensions:
    columns: 110
    lines: 35

  dynamic_padding: true

  padding:
    x: 2
    y: 2
