#!/bin/sh
set -uf

run() {
    delay="$1"
    shift
    cmd="$1"
    shift

    (
        sleep "$delay"
        [ -n "$(pidof "$cmd")" ] || exec "$cmd" "$@" > /dev/null 2>&1
    ) &
}

# disable bell
/usr/bin/xset b off
# set autorepeat (delay 200 ms, rate 40)
/usr/bin/xset r rate 200 40
# set black background
/usr/bin/xsetroot -solid black

run 2s "$HOME/bin/fbpanel"
run 3s "$HOME/bin/conky"

run 4s "/usr/bin/xscreensaver"
run 5s "/usr/bin/xss-lock" -l -- ~/bin/lock.sh

run 5s "$HOME/bin/easystroke"

#[ -x "$DOTFILES/opt/setlayout/setlayout" ] && "$DOTFILES/opt/setlayout/setlayout" 0 4 2 0
