#!/bin/bash

for f in "$DOTFILES"/.config/xinitrc.d/?*.sh ; do
    [ -f "$f" ] && . "$f"
done

my_run() {
    delay="$1"
    shift
    cmd="$1"
    shift

    (
        sleep "$delay"
        [ -n "$(pidof "$cmd")" ] || exec "$cmd" "$@" > /dev/null 2>&1
    ) &
}

my_run 1s xss-lock -l -- "$DOTFILES/bin/lock.sh"

if command -v xsecurelock &> /dev/null ; then
    true
elif command -v xscreensaver &> /dev/null ; then
    my_run 1s xscreensaver
fi

my_run 2s fbpanel
my_run 4s conky

if [ -f "$DOTFILES/private/.config/remind/default.rem" ] ; then
    my_run 4s remind -z -k"dunstify remind:\ %s" "$DOTFILES/private/.config/remind/default.rem"
fi
