#!/bin/sh
set -euf

run() {
    cmd="$1"
    shift

    if [ $# -ge 1 ] ; then
        sleep=$1
        shift
    fi

    (
        [ ! -z ${sleep:+x} ] && sleep "$sleep"
        [ -z "$(pidof "$cmd")" ] && exec "$cmd" "$@" > /dev/null 2>&1
    ) &
}

/usr/bin/xsetroot -solid black
/usr/bin/xset r rate 250 25
/usr/bin/xset b off

run "/usr/bin/uxterm" 1s

run "$HOME/bin/fbpanel" 2s
run "$HOME/bin/conky" 3s

run "/usr/bin/qxkb" 4s
run "/usr/bin/pasystray" 4s

run "/usr/bin/xscreensaver" 4s
run "/usr/bin/xss-lock" 5s -- xscreensaver-command -lock

run "$HOME/bin/easystroke" 5s

[ -x "$DOTFILES/opt/setlayout/setlayout" ] && "$DOTFILES/opt/setlayout/setlayout" 0 4 2 0
